apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: statusquarkusio-vypr
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mhms-tenant/status-quarkus-io/statusquarkusio-vypr@sha256:4fb2b1b9f1a4f0f217c1b4c94580618a1be571159c282efa6ddc808d58b0e60b
        name: my-java-quarkus
        resources: {}
status: {}
